### ISSUE TITLE
Would be a great feature to allow for includes/imports within the shader files.

### ISSUE THREAD

**Issue by iDVB** [glslify/glslify-loader#10]
We have a number of helper functions, libs that we manually paste into our shaders each time. Would be great to be able to include them instead and have the loader merge them in.

**Comment by Apidcloud** [comment]
Hello, @iDVB! Sorry for the delay.

I'm not sure I understand. How is this different from using something like:
`#pragma glslify: noise = require('glsl-noise/simplex/3d')`

Or was it different back in 2016?

Thanks!

**Comment by iDVB** [comment]
@Apidcloud Nw! Sorry but I've not worked with this loader since that time so, to be honest, you can likely close the issue unless someone else above can chime in to clarify. I literally can't remember what this was even about.

**Comment by Apidcloud** [comment]
Ah ok! Please create a new issue if you do remember.

Thanks!
