### ISSUE TITLE
Using glslify transformations with loader

### ISSUE THREAD

**Issue by wdanilo** [glslify/glslify-loader#18]
Hi!
I want to use glslify transformations like this one: https://www.npmjs.com/package/glslify-fancy-imports
Is it any way to tell the loader to pass "additional argument" when invoking the glslify command to use it?

**Comment by Apidcloud** [comment]
Hello, @wdanilo 

This should be addressed in #15. Please take a look and let us know. If it doesn't please open a new issue so we can get back at it.

Thanks 🙌
