### ISSUE TITLE
Webiste "http://stack.gl/glslify-loader/" Not Work [404]

### ISSUE THREAD

**Issue by mozgbrasil** [glslify/glslify-loader#20]
Hello good afternoon

I would like to inform you that the website is not working according to the image

![captura de tela de 2018-10-29 20-18-38](https://user-images.githubusercontent.com/17202780/47686028-db53cb00-dbb7-11e8-8f70-e881985d7f62.png)

**Comment by rreusser** [comment]
The site page is available at http://glslify.github.io/glslify-loader/

It's probably appropriate to switch this link out, but I'm not sure what the ultimate plan is for the stack.gl domain, which has currently lapsed.

**Comment by rreusser** [comment]
At any rate, I've fixed it for now.
