### ISSUE TITLE
webpack4?

### ISSUE THREAD

**Issue by rowild** [glslify/glslify-loader#21]
Is this package still maintained? 
Are there any new informations for webpack4?

Would be great to update the Readme.
Thank you!

**Comment by Apidcloud** [comment]
Hello, @rowild 

Yes. There's been a PR with that support for a while (see #15). I've also created a fork for that matter (see #19), and even released it to npm (scarlett-glslify-loader) if you wanna use it meanwhile.

We were waiting for people to actually try the PR before releasing it, but I'll check if we can do it soon.

Thanks!

**Comment by Apidcloud** [comment]
@rowild Version 2.0.0 was just released (see #15) with support to newer Webpack versions. Please feel free to open a new issue, should there be any problem with it!
