### ISSUE TITLE
can't use glsify when using loader

### ISSUE THREAD

**Issue by ajbeach2** [glslify/glslify-loader#7]
I can't figure out how to use glsify and glsify-loader. I don't understand why i have to transform the entire library to use it. How the heck do i use this with webpack?

my webpack config has this:

``` javascript
  module: {
    loaders: [

      { 
        test: /\.(glsl|frag|vert)$/, 
        loader: 'raw', exclude: /node_modules/
      },
      { 
        test: /\.(glsl|frag|vert)$/, 
        loader: 'glslify', exclude: /node_modules/
      }
]}
```

my main.js file looks like this:

``` javascript
var canvas   = document.body.appendChild(document.createElement('canvas'))
var gl       = require('gl-context')(canvas, function(){})

import glslify from 'glslify'
//both files are in the same directory as main.js
var shader = glslify({
  vert: './index.vert',
  frag: './index.frag'
})(gl)
```

but i am getting this error:

``` javascript
Uncaught Error: It appears that you're using glslify in browserify without its transform applied. Make sure that you've set up glslify as a source transform: https://github.com/substack/node-browserify#browserifytransform
```

**Comment by mattdesl** [comment]
Three issues: it looks like you are using old glslify syntax; glslify does not yet support es6 imports; and it looks like you aren't using the webpack-style (require) syntax in the readme of this module. 

If you'd like to use the classic glslify style syntax, see `ify-loader` module. There is an example in that readme. :)

**Comment by ajbeach2** [comment]
I was able to get it to work using the following:

``` javascript
import glShader from 'gl-shader'
import  glslify from 'glslify'

var shader = glShader(gl,
  glslify('./shader.vert'),
  glslify('./shader.frag')
)
```
