### ISSUE TITLE
Can't use glslify loader to load shader files in webpack

### ISSUE THREAD

**Issue by javidhsueh** [glslify/glslify-loader#8]
Now I'm working on a react component for rendering a graph visualization with stack.gl. I forked this boilerplate from here: github.com/survivejs/react-component-boilerplate

It has react, jsx, ES6, webpack. I'd like to load shaders using glslify-loader: github.com/stackgl/glslify-loader

But I've tried several way to load the shader,but I got a lot of error messages in the console, ex: should use browserify to transform ... no available loader .. compile error: 0:1...

Here's the repo I've created for debugging: https://github.com/javidhsueh/react-test

Please help me to figure how to use glslify with webpack.

Please see my question on stackoverflow
http://stackoverflow.com/questions/35314177/cant-use-glslify-loader-to-load-shader-files-in-webpack

**Comment by mattdesl** [comment]
A different approach than `glslify-loader` is to use `ify-loader`, which allows you to use the same syntax as in browserify. I think we will probably push for this approach going forward since it is more flexible than the Webpack style require overloads.

The readme contains a glslify example:
https://github.com/hughsk/ify-loader

**Comment by javidhsueh** [comment]
Hi, I followed the instructions in the ify-loader, but it still throw errors like this:
Uncaught Error: It appears that you're using glslify in browserify without its transform applied. Make sure that you've set up glslify as a source transform: https://github.com/substack/node-browserify#browserifytransform

Here's my code:
```
this._shader = createShader(gl,
glslify('./main.vertex.glsl'),
glslify('./main.fragment.glsl'));
```

My webpack config:

```
if (TARGET === 'start') {
  module.exports = merge(demoCommon, {
    devtool: 'eval-source-map',
    entry: config.paths.demo,
    plugins: [
      new webpack.DefinePlugin({
        'process.env.NODE_ENV': JSON.stringify('development')
      }),
      new HtmlWebpackPlugin({
        title: pkg.name + ' - ' + pkg.description,
        templateContent: renderJSX
      }),
      new webpack.HotModuleReplacementPlugin()
    ],
    module: {
      loaders: [
        {
          test: /\.css$/,
          loaders: ['style', 'css'],
          include: CSS_PATHS
        },
        {
          test: /\.jsx?$/,
          loaders: ['babel'],
          include: [
            config.paths.demo,
            config.paths.src
          ]
        }
      ],
      postLoaders: [
        {
          test: /\.js$/,
          loader: 'ify'
        }
      ]
    },
    devServer: {
      historyApiFallback: true,
      hot: true,
      inline: true,
      progress: true,
      host: process.env.HOST,
      port: process.env.PORT,
      stats: 'errors-only'
    }
  });
}
```

**Comment by javidhsueh** [comment]
Ok. I think I got it work now! Thanks

**Comment by chasevida** [comment]
@javidhsueh mind sharing how you configured this to work? I've tried both `glslify-loader` and `ify-loader` but get errors when there is any `pragma` require. I'm assuming it's because I don't understand the relation with browserify and there is perhaps some config there I'm missing.

**Comment by pedroalmeida415** [comment]
hey @chasevida did you manage to get the `#pragma` statements working? I'm having the same issue right now....
